version: '3.8'
#variables d'env
services:
  poll:
    build: ./poll # build avec schéma pour récup le dockerfile 
    ports:
      - "5000:80"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - poll-tier
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    restart: always

  worker:
    build: ./worker
    depends_on:
      - redis
      - db

    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password

    networks:
      - back-tier
    restart: always

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
       #load le schéma sql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql 
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    networks:
      - back-tier
      - result-tier
    restart: always

  result:
    build: ./result
    ports:
      - "5001:80"
    depends_on:
      - db

    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      
    networks:
      - result-tier
    restart: always

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
